# Creates a Drupal web app with MySQL database
# Usage: docker-compose up -d
# Notice that mysql server name is the same as the name of the mysql service ("mysql")

version: "2"
services:
  web:
    image: drupal:8.2.3-apache
    ports:
      - "8380:80"
    links:
      - mysql
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
